name: CI

on: 
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make deps

    - name: Linting
      run: make lint

    - name: Tests
      run: make tests

    - name: Build
      run: make build
