name: CI

on: 
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set node.js version @18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: make deps

    - name: Linting
      run: make lint

    - name: Tests
      run: CI=true make test

    - name: Build
      run: make build
